phpfpm55:
  build: ./docker/phpfpm55
  ports:
    - "80:80"
    - "443:443"
  links:
    - mysql:mysql
  volumes:
    # configs
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    # vhosts
    - ./../test:/var/www/test

data:
  image: busybox
  volumes:
    - /var/lib/mysql
  command: /bin/true

mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  volumes:
    - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: fghfgh
