version: '2'

services:
  php:
    image: rkit/docker-phpstack:7.1
    expose:
      - 9000
    links:
      - mysql:mysql
    volumes:
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./site:/var/www/site

  nginx:
    image: nginx:1.9.9
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./site:/var/www/site

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - data-mysql-5.7:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fghfgh

volumes:
  data-mysql-5.7:
    driver: local
